database_in=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new

# Define a standard security rule (Permissions, Inodes, Hashes)
NORMAL = p+i+n+u+g+s+m+c+sha256+sha512

# Directories to monitor for intrusions
/boot   NORMAL
/bin    NORMAL
/sbin   NORMAL
/lib    NORMAL
/opt    NORMAL
/usr    NORMAL
/root   NORMAL
/etc    NORMAL

# Exclude dynamic/volatile directories
!/dev
!/run
!/proc
!/sys
!/tmp
!/var/log
